# Generated by Django 3.2.6 on 2021-08-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(help_text='The starting year of the committee')),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(help_text='Ordering to use on the website')),
                ('position', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(blank=True, choices=[('CAI', 'Gonville & Caius'), ('CTH', "St Catharine's"), ('CHR', "Christ's"), ('CHU', 'Churchill'), ('CL', 'Clare'), ('CLH', 'Clare Hall'), ('CC', 'Corpus Christi'), ('DOW', 'Downing'), ('ED', "St Edmund's"), ('EM', 'Emmanuel'), ('F', 'Fitzwilliam'), ('G', 'Girton'), ('HO', 'Homerton'), ('HH', 'Hughes Hall'), ('JE', 'Jesus'), ('JN', "St John's"), ('K', "King's"), ('LC', 'Lucy Cavendish'), ('M', 'Magdalene'), ('MUR', 'Murray Edwards'), ('N', 'Newnham'), ('PEM', 'Pembroke'), ('PET', 'Peterhouse'), ('Q', "Queens'"), ('R', 'Robinson'), ('SE', 'Selwyn'), ('SID', 'Sidney Sussex'), ('TH', 'Trinity Hall'), ('T', 'Trinity'), ('W', 'Wolfson'), ('DAR', 'Darwin'), ('NA', 'N/A')], max_length=6)),
                ('email', models.CharField(max_length=100, null=True)),
                ('is_publications', models.BooleanField(default=False)),
                ('photo', models.CharField(max_length=100, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.committee')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
