# Generated by Django 3.2.6 on 2021-08-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('crsid', models.CharField(max_length=8)),
                ('alternative_email', models.CharField(blank=True, max_length=35, null=True)),
                ('college', models.CharField(blank=True, choices=[('CAIUS', 'Gonville & Caius'), ('CATH', "St Catherine's"), ('CHRST', "Christ's"), ('CHUR', 'Churchill'), ('CLARE', 'Clare'), ('CLAREH', 'Clare Hall'), ('CORP', 'Corpus Christi'), ('DOWN', 'Downing'), ('EDM', "St Edmund's"), ('EMM', 'Emmanuel'), ('FITZ', 'Fitzwilliam'), ('GIRT', 'Girton'), ('HOM', 'Homerton'), ('HUGH', 'Hughes Hall'), ('JESUS', 'Jesus'), ('JOHNS', "St John's"), ('KINGS', "King's"), ('LCC', 'Lucy Cavendish'), ('MAGD', 'Magdalene'), ('NEWH', 'Murray Edwards'), ('NEWN', 'Newnham'), ('PEMB', 'Pembroke'), ('PET', 'Peterhouse'), ('QUEN', "Queens'"), ('ROBIN', 'Robinson'), ('SEL', 'Selwyn'), ('SID', 'Sidney Sussex'), ('TRINH', 'Trinity Hall'), ('TRIN', 'Trinity'), ('WOLFC', 'Wolfson'), ('DRWN', 'Darwin'), ('NA', 'N/A')], max_length=6)),
                ('life_member', models.BooleanField()),
                ('membership_start', models.DateField()),
                ('membership_end', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
